name: XCTest Results

on:
   push:
     branches:
       - main
   workflow_dispatch:
jobs:
   xctest_html_report:
     name: XCTestHTMLReport
     runs-on: macos-12
     steps:
       - uses: actions/checkout@v3.1.0

       - run: brew install xctesthtmlreport

       - run: xcodebuild test -scheme XCTestReport -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' -resultBundlePath TestResult | xcpretty

       - run: xchtmlreport TestResult.xcresult

       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3.9.2
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./
           destination_dir: ${{ github.run_id }}
           exclude_assets: '.github,XCTestReport.xcodeproj,XCTestReport,XCTestReportUITests'
